// GENERATED by tools/generate_constellation_table.py; do not edit by hand.
//
// The IAU constellation boundaries, Delporte (1930) as rearranged for lookup by
// Roman (1987, PASP 99, 695) and distributed as VizieR VI/42, plus the IAU's official
// constellation names from VizieR's own constellation table.
//
// Right ascensions are HOURS and declinations DEGREES, both in the mean equinox of
// B1875, which is the frame Delporte drew the boundaries in. A position in any other
// frame has to be brought here first; see Core/BesselianFrames.cs.
//
// RECORD ORDER IS PART OF THE DATA. Roman sorted the arcs by declination floor and
// then by eastern terminus so that the first bracketing record encountered in a
// forward scan is the answer. Re-sorting this array breaks the lookup.

namespace ExoInstruments.Core
{
    internal static class ConstellationTable
    {
        /// <summary>Western edge of each boundary arc, hours of right ascension, B1875.</summary>
        public static readonly double[] RaLowHours =
        {
            0.0, 8.0, 21.0, 18.0, 0.0, 9.1667, 0.0, 10.6667,
            17.5, 20.1667, 0.0, 11.5, 16.5333, 20.1667, 7.9667, 9.1667,
            13.0, 3.1, 20.4167, 11.3333, 0.0, 14.0, 23.5833, 12.0,
            13.5, 23.1667, 6.1, 20.0, 20.5367, 7.0, 7.9667, 19.7667,
            20.0, 22.8667, 0.0, 19.4167, 1.7, 2.4333, 3.1, 22.3167,
            5.0, 14.0333, 14.4167, 3.1667, 22.1333, 20.6, 0.0, 6.1,
            12.0833, 15.25, 21.9667, 3.3333, 22.8667, 15.75, 2.0417, 17.0,
            0.0, 1.3667, 6.5, 23.3333, 13.5, 0.0, 23.5833, 18.175,
            18.2333, 19.0833, 1.6667, 8.4167, 0.1667, 12.0, 6.8, 21.9083,
            21.875, 19.1667, 9.1667, 10.1667, 15.4333, 15.75, 9.25, 0.0,
            2.5167, 19.3583, 4.5, 21.7333, 21.875, 6.5333, 7.3667, 0.0,
            22.0, 22.8167, 22.8667, 2.5667, 10.7833, 12.0, 7.75, 9.25,
            0.7167, 15.1833, 23.5, 12.3333, 23.75, 13.9583, 2.4167, 2.7167,
            4.5, 18.175, 11.0, 19.6667, 4.75, 9.8833, 13.25, 0.0,
            1.4083, 5.8833, 7.8833, 20.9167, 19.2583, 1.9167, 16.1667, 15.0833,
            15.1833, 18.3667, 10.75, 18.8667, 1.6667, 0.7167, 10.5, 21.25,
            5.7, 0.0667, 15.9167, 5.8833, 19.8333, 18.8667, 0.1417, 20.25,
            7.8083, 20.5667, 19.25, 3.2833, 18.8667, 5.7, 6.2167, 19.0,
            4.9667, 15.9167, 19.8333, 4.6167, 5.3333, 12.8333, 17.25, 11.8667,
            7.5, 16.75, 0.0, 5.6, 7.0, 21.1167, 6.3083, 18.25,
            20.875, 21.05, 11.5167, 6.2417, 6.9333, 7.8083, 23.8333, 1.6667,
            20.1417, 13.5, 22.75, 7.925, 9.25, 18.25, 18.6622, 20.8333,
            7.0, 18.25, 16.0833, 18.25, 21.4667, 0.0, 18.5833, 20.3,
            20.8333, 21.3333, 22.0, 21.6667, 7.0167, 3.5833, 4.6167, 7.2,
            14.6667, 17.8333, 2.65, 3.2833, 15.0833, 4.6667, 5.8333, 17.8333,
            18.25, 18.5833, 22.75, 10.75, 11.5167, 0.0, 23.8333, 14.25,
            15.9167, 20.0, 21.3333, 17.1667, 5.8333, 4.9167, 5.0833, 8.0833,
            9.5833, 11.8333, 17.5833, 18.8667, 4.8333, 20.5333, 17.1667, 18.25,
            8.3667, 16.2667, 8.5833, 10.75, 16.2667, 15.6667, 12.5833, 12.8333,
            9.0833, 1.6667, 2.65, 10.8333, 11.8333, 14.25, 16.2667, 0.0,
            21.3333, 21.8667, 23.8333, 9.75, 4.7, 4.8333, 20.0, 10.25,
            12.5833, 14.9167, 15.6667, 4.5833, 16.75, 17.6, 10.5833, 6.1167,
            12.25, 10.8333, 3.5, 8.3667, 4.2667, 17.8333, 21.3333, 23.0,
            3.0, 9.3667, 0.0, 1.6667, 3.8667, 23.3333, 14.1667, 15.6667,
            16.0, 4.8333, 5.0, 8.0, 3.4167, 16.4208, 17.8333, 19.1667,
            20.3333, 3.0, 4.5, 15.3333, 0.0, 2.6667, 4.0833, 4.2667,
            21.3333, 6.0, 8.0, 2.4167, 3.8333, 0.0, 6.0, 8.1667,
            3.5, 3.8333, 0.0, 2.1667, 4.5, 15.05, 8.45, 6.1667,
            11.8333, 14.1667, 15.05, 4.0, 8.8333, 11.0, 17.5, 18.0,
            22.0, 3.2, 5.0, 6.5, 0.0, 1.3333, 23.3333, 4.3333,
            15.3333, 20.3333, 5.5, 15.1667, 16.4208, 14.9167, 16.5833, 6.0,
            6.8333, 11.25, 11.8333, 12.8333, 13.5, 16.75, 2.1667, 3.2,
            14.75, 16.8333, 17.5, 22.0, 4.5833, 13.6667, 14.75, 0.0,
            3.5, 6.5833, 9.0333, 11.25, 18.0, 21.3333, 23.3333, 0.75,
            0.0, 7.6667, 13.6667, 3.5, 0.0,
        };

        /// <summary>Eastern edge of each boundary arc, hours of right ascension, B1875.</summary>
        public static readonly double[] RaHighHours =
        {
            24.0, 14.5, 23.0, 21.0, 8.0, 10.6667, 5.0, 14.5,
            18.0, 21.0, 3.5083, 13.5833, 17.5, 20.6667, 9.1667, 11.3333,
            16.5333, 3.4167, 20.6667, 12.0, 0.3333, 15.6667, 24.0, 13.5,
            14.4167, 23.5833, 7.0, 20.4167, 20.6, 7.9667, 8.4167, 20.0,
            20.5367, 23.1667, 2.4333, 19.7667, 1.9083, 3.1, 3.1667, 22.8667,
            6.1, 14.4167, 19.4167, 3.3333, 22.3167, 21.9667, 1.7, 6.5,
            13.5, 15.75, 22.1333, 5.0, 23.3333, 17.0, 2.5167, 18.2333,
            1.3667, 1.6667, 6.8, 24.0, 14.0333, 1.1167, 24.0, 18.2333,
            19.0833, 19.1667, 2.0417, 9.1667, 0.8667, 12.0833, 7.3667, 21.9667,
            21.9083, 19.4, 10.1667, 10.7833, 15.75, 16.3333, 9.5833, 2.5167,
            2.5667, 19.4, 4.6917, 21.875, 22.0, 7.3667, 7.75, 2.0,
            22.8167, 22.8667, 23.5, 2.7167, 11.0, 12.3333, 9.25, 9.8833,
            1.4083, 15.4333, 23.75, 13.25, 24.0, 14.0333, 2.7167, 4.5,
            4.75, 19.3583, 12.0, 20.9167, 5.8833, 10.5, 13.9583, 0.0667,
            1.6667, 6.5333, 8.0, 21.7333, 19.6667, 2.4167, 16.3333, 15.1833,
            16.1667, 18.8667, 11.0, 19.2583, 1.9167, 0.85, 10.75, 21.4167,
            5.8833, 0.1417, 16.0333, 6.2167, 20.25, 19.25, 0.85, 20.5667,
            7.8833, 21.25, 19.8333, 3.3667, 19.0, 5.7667, 6.3083, 19.8333,
            5.3333, 16.0833, 20.25, 4.9667, 5.6, 13.5, 18.25, 12.8333,
            7.8083, 17.25, 0.1417, 5.7667, 7.5, 21.3333, 6.9333, 18.8667,
            21.05, 21.1167, 11.8667, 6.3083, 7.0, 7.925, 24.0, 3.2833,
            20.3, 15.0833, 23.8333, 9.25, 10.75, 18.6622, 18.8667, 20.875,
            7.0167, 18.425, 16.75, 18.425, 21.6667, 2.0, 18.8667, 20.8333,
            21.3333, 21.4667, 22.75, 22.0, 7.2, 4.6167, 4.6667, 8.0833,
            15.0833, 18.25, 3.2833, 3.5833, 16.2667, 5.0833, 6.2417, 17.9667,
            18.5833, 18.8667, 23.8333, 11.5167, 11.8333, 0.3333, 24.0, 14.6667,
            16.2667, 20.5333, 21.8667, 17.9667, 8.0833, 5.0833, 5.8333, 8.3667,
            10.75, 12.8333, 17.6667, 20.0, 4.9167, 21.3333, 18.25, 18.8667,
            8.5833, 16.375, 9.0833, 10.8333, 16.375, 15.9167, 12.8333, 14.25,
            9.75, 2.65, 3.75, 11.8333, 12.5833, 14.9167, 16.75, 1.6667,
            21.8667, 23.8333, 24.0, 10.25, 4.8333, 6.1167, 21.3333, 10.5833,
            14.9167, 15.6667, 16.0, 4.7, 17.6, 17.8333, 10.8333, 7.3667,
            12.5833, 12.25, 3.75, 9.3667, 4.5833, 19.1667, 23.0, 23.3333,
            3.5, 11.0, 1.6667, 3.0, 4.2667, 24.0, 14.9167, 16.0,
            16.4208, 5.0, 6.5833, 8.3667, 3.8667, 17.8333, 19.1667, 20.3333,
            21.3333, 3.4167, 4.8333, 15.6667, 2.3333, 3.0, 4.2667, 4.5,
            22.0, 8.0, 8.1667, 2.6667, 4.0833, 1.8333, 6.1667, 8.45,
            3.8333, 4.0, 1.5833, 2.4167, 5.0, 15.3333, 8.8333, 6.5,
            12.8333, 15.05, 15.3333, 4.3333, 11.0, 11.25, 18.0, 20.3333,
            23.3333, 3.5, 5.5, 6.8333, 1.3333, 2.1667, 24.0, 4.5833,
            16.4208, 21.3333, 6.0, 15.3333, 16.5833, 15.1667, 16.75, 6.8333,
            9.0333, 11.8333, 12.8333, 14.5333, 13.6667, 16.8333, 3.2, 4.5833,
            14.9167, 17.5, 18.0, 23.3333, 6.5833, 14.75, 17.0, 1.3333,
            4.5833, 9.0333, 11.25, 13.6667, 21.3333, 23.3333, 24.0, 1.3333,
            3.5, 13.6667, 18.0, 7.6667, 24.0,
        };

        /// <summary>Southern edge of each boundary arc, degrees of declination, B1875.</summary>
        public static readonly double[] DecLowDeg =
        {
            88.0, 86.5, 86.1667, 86.0, 85.0, 82.0, 80.0, 80.0,
            80.0, 80.0, 77.0, 77.0, 75.0, 75.0, 73.5, 73.5,
            70.0, 68.0, 67.0, 66.5, 66.0, 66.0, 66.0, 64.0,
            63.0, 63.0, 62.0, 61.5, 60.9167, 60.0, 60.0, 59.5,
            59.5, 59.0833, 58.5, 58.0, 57.5, 57.0, 57.0, 56.25,
            56.0, 55.5, 55.5, 55.0, 55.0, 54.8333, 54.0, 54.0,
            53.0, 53.0, 52.75, 52.5, 52.5, 51.5, 50.5, 50.5,
            50.0, 50.0, 50.0, 50.0, 48.5, 48.0, 48.0, 47.5,
            47.5, 47.5, 47.0, 47.0, 46.0, 45.0, 44.5, 44.0,
            43.75, 43.5, 42.0, 40.0, 40.0, 40.0, 39.75, 36.75,
            36.75, 36.5, 36.0, 36.0, 36.0, 35.5, 35.5, 35.0,
            35.0, 34.5, 34.5, 34.0, 34.0, 34.0, 33.5, 33.5,
            33.0, 33.0, 32.0833, 32.0, 31.3333, 30.75, 30.6667, 30.6667,
            30.0, 30.0, 29.0, 29.0, 28.5, 28.5, 28.5, 28.0,
            28.0, 28.0, 28.0, 28.0, 27.5, 27.25, 27.0, 26.0,
            26.0, 26.0, 25.5, 25.5, 25.0, 23.75, 23.5, 23.5,
            22.8333, 22.0, 22.0, 21.5, 21.25, 21.0833, 21.0, 20.5,
            20.0, 19.5, 19.1667, 19.0, 18.5, 18.0, 17.5, 16.1667,
            16.0, 16.0, 15.75, 15.5, 15.5, 15.0, 14.3333, 14.0,
            13.5, 12.8333, 12.5, 12.5, 12.5, 12.5, 12.0, 12.0,
            11.8333, 11.8333, 11.0, 10.0, 10.0, 10.0, 10.0, 9.9167,
            8.5, 8.0, 7.5, 7.0, 7.0, 6.25, 6.25, 6.0,
            5.5, 4.5, 4.0, 3.0, 2.75, 2.0, 2.0, 2.0,
            2.0, 2.0, 2.0, 1.75, 1.5, 0.0, 0.0, 0.0,
            0.0, 0.0, -1.75, -1.75, -3.25, -4.0, -4.0, -4.0,
            -4.0, -4.0, -4.0, -6.0, -6.0, -7.0, -7.0, -8.0,
            -8.0, -9.0, -9.0, -10.0, -11.0, -11.0, -11.0, -11.0,
            -11.0, -11.0, -11.6667, -12.0333, -14.5, -15.0, -16.0, -16.0,
            -17.0, -18.25, -19.0, -19.0, -19.25, -20.0, -22.0, -22.0,
            -24.0, -24.3833, -24.3833, -24.5, -24.5, -24.5, -24.5833, -25.5,
            -25.5, -25.5, -25.5, -26.5, -27.25, -27.25, -28.0, -29.1667,
            -29.5, -29.5, -29.5, -30.0, -30.0, -30.0, -31.1667, -33.0,
            -33.0, -35.0, -36.0, -36.75, -37.0, -37.0, -37.0, -37.0,
            -39.5833, -39.75, -40.0, -40.0, -40.0, -40.0, -42.0, -42.0,
            -42.0, -43.0, -43.0, -43.0, -44.0, -45.5, -45.5, -45.5,
            -45.5, -46.0, -46.5, -48.0, -48.1667, -49.0, -49.0, -49.0,
            -50.0, -50.75, -50.75, -51.0, -51.0, -51.5, -52.5, -53.0,
            -53.1667, -53.1667, -53.5, -54.0, -54.0, -54.0, -54.5, -55.0,
            -55.0, -55.0, -55.0, -56.5, -56.5, -56.5, -57.0, -57.0,
            -57.0, -57.5, -57.5, -58.0, -58.5, -58.5, -58.5, -59.0,
            -60.0, -60.0, -61.0, -61.0, -61.0, -63.5833, -63.5833, -64.0,
            -64.0, -64.0, -64.0, -64.0, -65.0, -65.0, -67.5, -67.5,
            -67.5, -67.5, -67.5, -67.5, -70.0, -70.0, -70.0, -75.0,
            -75.0, -75.0, -75.0, -75.0, -75.0, -75.0, -75.0, -76.0,
            -82.5, -82.5, -82.5, -85.0, -90.0,
        };

        /// <summary>Three-letter IAU abbreviation owning each arc, parallel to the arrays above.</summary>
        public static readonly string[] Abbreviations =
        {
            "UMi", "UMi", "UMi", "UMi", "Cep", "Cam", "Cep", "Cam",
            "UMi", "Dra", "Cep", "Cam", "UMi", "Cep", "Cam", "Dra",
            "UMi", "Cas", "Dra", "Dra", "Cep", "UMi", "Cep", "Dra",
            "Dra", "Cep", "Cam", "Dra", "Cep", "Cam", "UMa", "Dra",
            "Cep", "Cep", "Cas", "Dra", "Cas", "Cas", "Cam", "Cep",
            "Cam", "UMa", "Dra", "Cam", "Cep", "Cep", "Cas", "Lyn",
            "UMa", "Dra", "Cep", "Cam", "Cas", "Dra", "Per", "Dra",
            "Cas", "Per", "Lyn", "Cas", "UMa", "Cas", "Cas", "Her",
            "Dra", "Cyg", "Per", "UMa", "Cas", "UMa", "Lyn", "Cyg",
            "Cyg", "Cyg", "UMa", "UMa", "Boo", "Her", "Lyn", "And",
            "Per", "Lyr", "Per", "Cyg", "Lac", "Aur", "Lyn", "And",
            "Lac", "Lac", "And", "Per", "UMa", "CVn", "Lyn", "LMi",
            "And", "Boo", "And", "CVn", "And", "CVn", "Tri", "Per",
            "Aur", "Lyr", "UMa", "Cyg", "Aur", "LMi", "CVn", "And",
            "Tri", "Aur", "Gem", "Cyg", "Cyg", "Tri", "CrB", "Boo",
            "CrB", "Lyr", "LMi", "Lyr", "Tri", "Psc", "LMi", "Vul",
            "Tau", "And", "Ser", "Gem", "Vul", "Vul", "And", "Vul",
            "Gem", "Vul", "Vul", "Ari", "Sge", "Ori", "Gem", "Sge",
            "Tau", "Her", "Sge", "Tau", "Tau", "Com", "Her", "Com",
            "Gem", "Her", "Peg", "Tau", "Gem", "Peg", "Gem", "Her",
            "Del", "Peg", "Leo", "Ori", "Gem", "Cnc", "Peg", "Ari",
            "Del", "Boo", "Peg", "Cnc", "Leo", "Oph", "Aql", "Del",
            "CMi", "Ser", "Her", "Oph", "Peg", "Psc", "Ser", "Del",
            "Equ", "Peg", "Peg", "Peg", "CMi", "Tau", "Ori", "CMi",
            "Vir", "Oph", "Cet", "Tau", "Ser", "Ori", "Ori", "Ser",
            "Ser", "Aql", "Psc", "Leo", "Vir", "Psc", "Psc", "Vir",
            "Oph", "Aql", "Aqr", "Oph", "Mon", "Eri", "Ori", "Hya",
            "Sex", "Vir", "Oph", "Aql", "Eri", "Aqr", "Ser", "Sct",
            "Hya", "Oph", "Hya", "Crt", "Sco", "Lib", "Crv", "Vir",
            "Hya", "Cet", "Eri", "Crt", "Crv", "Lib", "Oph", "Cet",
            "Cap", "Aqr", "Cet", "Hya", "Eri", "Lep", "Cap", "Hya",
            "Hya", "Lib", "Sco", "Eri", "Oph", "Sgr", "Hya", "CMa",
            "Hya", "Hya", "For", "Pyx", "Eri", "Sgr", "PsA", "Scl",
            "For", "Ant", "Scl", "For", "Eri", "Scl", "Cen", "Lup",
            "Sco", "Cae", "Col", "Pup", "Eri", "Sco", "CrA", "Sgr",
            "Mic", "Eri", "Cae", "Lup", "Phe", "Eri", "Hor", "Cae",
            "Gru", "Pup", "Vel", "Eri", "Hor", "Phe", "Car", "Vel",
            "Hor", "Dor", "Phe", "Eri", "Pic", "Lup", "Vel", "Car",
            "Cen", "Lup", "Nor", "Dor", "Vel", "Cen", "Ara", "Tel",
            "Gru", "Hor", "Pic", "Car", "Phe", "Eri", "Phe", "Dor",
            "Nor", "Ind", "Pic", "Cir", "Ara", "Cir", "Ara", "Pic",
            "Car", "Cen", "Cru", "Cen", "Cir", "Ara", "Hor", "Ret",
            "Cir", "Ara", "Pav", "Tuc", "Dor", "Cir", "TrA", "Tuc",
            "Hyi", "Vol", "Car", "Mus", "Pav", "Ind", "Tuc", "Tuc",
            "Hyi", "Cha", "Aps", "Men", "Oct",
        };

        /// <summary>The 88 abbreviations, alphabetical. AllNames, AllMeanings and AllGenitives run parallel to this.</summary>
        public static readonly string[] AllAbbreviations =
        {
            "And", "Ant", "Aps", "Aql", "Aqr", "Ara", "Ari", "Aur",
            "Boo", "CMa", "CMi", "CVn", "Cae", "Cam", "Cap", "Car",
            "Cas", "Cen", "Cep", "Cet", "Cha", "Cir", "Cnc", "Col",
            "Com", "CrA", "CrB", "Crt", "Cru", "Crv", "Cyg", "Del",
            "Dor", "Dra", "Equ", "Eri", "For", "Gem", "Gru", "Her",
            "Hor", "Hya", "Hyi", "Ind", "LMi", "Lac", "Leo", "Lep",
            "Lib", "Lup", "Lyn", "Lyr", "Men", "Mic", "Mon", "Mus",
            "Nor", "Oct", "Oph", "Ori", "Pav", "Peg", "Per", "Phe",
            "Pic", "PsA", "Psc", "Pup", "Pyx", "Ret", "Scl", "Sco",
            "Sct", "Ser", "Sex", "Sge", "Sgr", "Tau", "Tel", "TrA",
            "Tri", "Tuc", "UMa", "UMi", "Vel", "Vir", "Vol", "Vul",
        };

        /// <summary>The IAU's official constellation names.</summary>
        public static readonly string[] AllNames =
        {
            "Andromeda", "Antlia", "Apus", "Aquila", "Aquarius", "Ara", "Aries", "Auriga",
            "Boötes", "Canis Major", "Canis Minor", "Canes Venatici", "Caelum", "Camelopardalis", "Capricornus", "Carina",
            "Cassiopeia", "Centaurus", "Cepheus", "Cetus", "Chamaeleon", "Circinus", "Cancer", "Columba",
            "Coma Berenices", "Corona Australis", "Corona Borealis", "Crater", "Crux", "Corvus", "Cygnus", "Delphinus",
            "Dorado", "Draco", "Equuleus", "Eridanus", "Fornax", "Gemini", "Grus", "Hercules",
            "Horologium", "Hydra", "Hydrus", "Indus", "Leo Minor", "Lacerta", "Leo", "Lepus",
            "Libra", "Lupus", "Lynx", "Lyra", "Mensa", "Microscopium", "Monoceros", "Musca",
            "Norma", "Octans", "Ophiuchus", "Orion", "Pavo", "Pegasus", "Perseus", "Phoenix",
            "Pictor", "Piscis Austrinus", "Pisces", "Puppis", "Pyxis", "Reticulum", "Sculptor", "Scorpius",
            "Scutum", "Serpens", "Sextans", "Sagitta", "Sagittarius", "Taurus", "Telescopium", "Triangulum Australe",
            "Triangulum", "Tucana", "Ursa Major", "Ursa Minor", "Vela", "Virgo", "Volans", "Vulpecula",
        };

        /// <summary>What each Latin name means, as the IAU's own table glosses it ("the Sea Monster").</summary>
        public static readonly string[] AllMeanings =
        {
            "the Chained Maiden", "the Air Pump", "the Bird of Paradise", "the Eagle", "the Water Bearer", "the Altar", "the Ram", "the Charioteer",
            "the Herdsman", "the Great Dog", "the Lesser Dog", "the Hunting Dogs", "the Engraving Tool", "the Giraffe", "the Sea Goat", "the Keel",
            "the Seated Queen", "the Centaur", "the King", "the Sea Monster", "the Chameleon", "the Drawing Compass", "the Crab", "the Dove",
            "the Bernice's Hair", "the Southern Crown", "the Northern Crown", "the Cup", "the Southern Cross", "the Crow", "the Swan", "the Dolphin",
            "the Swordfish", "the Dragon", "the Little Horse", "the River", "the Furnace", "the Twins", "the Crane", "the Hercules",
            "the Clock", "the Female Water Snake", "the Male Water Snake", "the Indian", "the Lesser Lion", "the Lizard", "the Lion", "the Hare",
            "the Scales", "the Wolf", "the Lynx", "the Lyre", "the Table Mountain", "the Microscope", "the Unicorn", "the Fly",
            "the Carpenter's Square", "the Octant", "the Serpent Bearer", "the Hunter", "the Peacock", "the Winged Horse", "the Hero", "the Phoenix",
            "the Painter's Easel", "the Southern Fish", "the Fishes", "the Stern", "the Mariner Compass", "the Reticle", "the Sculptor", "the Scorpion",
            "the Shield", "the Serpent", "the Sextant", "the Arrow", "the Archer", "the Bull", "the Telescope", "the Southern Triangle",
            "the Triangle", "the Toucan", "the Great Bear", "the Little Bear", "the Sails", "the Maiden", "the Flying Fish", "the Fox",
        };

        /// <summary>The genitive, which is the form that appears in Bayer and Flamsteed star names ("Pegasi" in 51 Pegasi).</summary>
        public static readonly string[] AllGenitives =
        {
            "Andromedae", "Antliae", "Apodis", "Aquilae", "Aquarii", "Arae", "Arietis", "Aurigae",
            "Boötis", "Canis Majoris", "Canis Minoris", "Canum Venaticorum", "Caeli", "Camelopardalis", "Capricorni", "Carinae",
            "Cassiopeiae", "Centauri", "Cephei", "Ceti", "Chamaeleontis", "Circini", "Cancri", "Columbae",
            "Comae Berenices", "Coronae Australis", "Coronae Borealis", "Crateris", "Crucis", "Corvi", "Cygni", "Delphini",
            "Doradus", "Draconis", "Equulei", "Eridani", "Fornacis", "Geminorum", "Gruis", "Herculis",
            "Horologii", "Hydrae", "Hydri", "Indi", "Leonis Minoris", "Lacertae", "Leonis", "Leporis",
            "Librae", "Lupi", "Lyncis", "Lyrae", "Mensae", "Microscopii", "Monocerotis", "Muscae",
            "Normae", "Octantis", "Ophiuchi", "Orionis", "Pavonis", "Pegasi", "Persei", "Phoenicis",
            "Pictoris", "Piscis Austrini", "Piscium", "Puppis", "Pyxidis", "Reticuli", "Sculptoris", "Scorpii",
            "Scuti", "Serpentis", "Sextantis", "Sagittae", "Sagittarii", "Tauri", "Telescopii", "Trianguli Australis",
            "Trianguli", "Tucanae", "Ursae Majoris", "Ursae Minoris", "Velorum", "Virginis", "Volantis", "Vulpeculae",
        };
    }
}
