using System;

namespace ExoInstruments.Core
{
    /// <summary>
    /// Persistence in an HgCdTe infrared array, as STScI's own persistence pipeline computes it for
    /// WFC3/IR. This is a DIFFERENT MODEL from Core.DetectorPersistence, not a re-parameterisation
    /// of it, and the difference is physical rather than cosmetic.
    ///
    /// A CCD's residual surface image is charge held at the silicon-oxide interface and released
    /// with the exponential law a trap depth implies, so Core.DetectorPersistence carries two
    /// exponentials. An infrared array traps charge in defects within the detector DIODES, which
    /// have a broad and continuous distribution of trap and release times, and the sum of that
    /// distribution is measured to decay as a POWER LAW in time rather than as any small number of
    /// exponentials. Long, Baggett &amp; MacKenty (2015, WFC3 ISR 2015-15) state it in those terms and
    /// fit it that way. Two technologies, two trap populations, two laws; using one code path for
    /// both would mean choosing which of the two measurements to contradict.
    ///
    /// THE MODEL, exactly as published (ISR 2015-15, Eq. 1, the "Fermi model"):
    ///
    ///     P(x, t) = A * [ 1 / (exp(-(x - x0)/dx) + 1) ] * (x/x0)^alpha * (t/1000 s)^(-gamma)
    ///
    /// where P is the persistence RATE in electrons per second at a time t after the end of an
    /// earlier exposure that left the pixel with a fluence x in electrons. The four factors are, in
    /// the report's own reading of them:
    ///
    ///   * A, a normalisation in e-/s;
    ///   * a Fermi-like term describing the rapid rise in persistence near saturation, in terms of
    ///     a characteristic fluence x0 and a width dx;
    ///   * a power law in fluence with index alpha, describing the slow further rise generated by
    ///     very high fluences;
    ///   * a power law in time with index gamma, describing the decay.
    ///
    /// ALL FIVE PARAMETERS ARE FUNCTIONS OF THE STIMULUS EXPOSURE TIME, and that is the whole point
    /// of the 2015 report. The model STScI used before it depended only on fluence and elapsed
    /// time, which amounts to assuming the traps fill instantaneously; the measurements show they
    /// do not, so how long the pixel sat full matters. Table 2 of the report gives the fitted
    /// parameters at eight stimulus exposure times from 49 s to 1402 s, and the report's own
    /// prescription for anything in between is to interpolate linearly on exposure time. That is
    /// what InterpolateParameters does, and it is the same thing version 3.0.1 of STScI's
    /// persistence pipeline does.
    ///
    /// WHAT THE TABLE SAYS, read as physics rather than as numbers (the report lists these four
    /// trends itself, and the harness asserts every one of them holds in the interpolated model):
    ///
    ///   1. A increases with the length of the stimulus exposure.
    ///   2. x0 decreases with it, because even at low fluence there are some traps, and those traps
    ///      tend to have the longer trapping times.
    ///   3. alpha decreases with it, sharpening the knee.
    ///   4. gamma decreases with it, so persistence after a long exposure lasts longer.
    ///
    /// ONE STIMULUS, NOT A SUM. Where several earlier exposures could each cause persistence, the
    /// published pipeline counts only the one that would cause the most persistence in the current
    /// image, and does not add them. That is a stated simplification of the real physics and it is
    /// reproduced here rather than improved on, because the fitted parameters were derived under it
    /// and using them under a different rule would apply them outside their own calibration.
    ///
    /// THE MODEL'S OWN ACCURACY IS PUBLISHED, which is rare enough to be worth using. Table 3 of the
    /// report tabulates the mean absolute error between the Fermi model and the data over six
    /// fluence/time intervals per visit; across all eight visits it runs from 0.0014 to 0.0275
    /// e-/s, and the report notes the model tends to under-predict at high fluence by about
    /// 0.02 e-/s after 1500 s and to over-predict around 70,000 e-. Carried below as a named
    /// constant so the pipeline can state its own uncertainty instead of implying it has none.
    ///
    /// Pure C#, no Unity dependency.
    /// </summary>
    public static class HgCdTePersistence
    {
        /// <summary>
        /// Table 2 of WFC3 ISR 2015-15: "Parameters of Fermi models for Various Exposure Times".
        /// Columns are the stimulus exposure time in seconds, A in e-/s, x0 in electrons, dx in
        /// electrons, alpha, and gamma. Transcribed exactly; no row is interpolated or smoothed
        /// here, and nothing is rounded.
        /// </summary>
        public static readonly double[] StimulusExposureSeconds = { 49, 99, 149, 199, 499, 799, 1102, 1402 };
        public static readonly double[] AmplitudeElectronsPerSecond = { 0.251, 0.282, 0.280, 0.287, 0.317, 0.323, 0.329, 0.328 };
        public static readonly double[] CharacteristicFluenceElectrons = { 97196, 96140, 91849, 90138, 83844, 78415, 75202, 73500 };
        public static readonly double[] FluenceWidthElectrons = { 17346, 17889, 18067, 18612, 18909, 17547, 17504, 17755 };
        public static readonly double[] FluencePowerAlpha = { 0.206, 0.197, 0.187, 0.178, 0.146, 0.141, 0.131, 0.126 };
        public static readonly double[] DecayIndexGamma = { 1.269, 1.232, 1.096, 1.078, 1.005, 0.964, 0.942, 0.921 };

        /// <summary>
        /// The nominal saturation level of the WFC3/IR detector, as ISR 2015-15's own Table 1
        /// footnote defines it when counting saturated pixels: 70,000 electrons.
        ///
        /// Carried here rather than taken from the instrument's full well because it is the number
        /// the persistence measurement itself was expressed against, and the handbooks quote
        /// different figures elsewhere for different purposes (see VisualTelescopeCatalog).
        /// </summary>
        public const double NominalSaturationElectrons = 70000.0;

        /// <summary>
        /// Below this fluence the report measures very little persistence: "there is very little
        /// persistence (&lt; 0.05 e/s) below a fluence of 30,000 e, especially beyond about 500 s
        /// after the end of the stimulus exposure."
        ///
        /// Not used as a cutoff - the Fermi form already falls away there on its own, and imposing
        /// a hard floor would contradict the fit. It is here as the comparator the harness checks
        /// the model against.
        /// </summary>
        public const double LowPersistenceFluenceElectrons = 30000.0;
        public const double LowPersistenceRateElectronsPerSecond = 0.05;

        /// <summary>
        /// The published mean absolute error of this model against the data, from Table 3 of ISR
        /// 2015-15: the smallest and largest of the 48 tabulated values, in e-/s.
        ///
        /// This is the model's own uncertainty and it is a real quantity, not a guess about one.
        /// </summary>
        public const double ModelErrorBestElectronsPerSecond = 0.0014;
        public const double ModelErrorWorstElectronsPerSecond = 0.0275;

        /// <summary>The five Fermi parameters at one stimulus exposure time.</summary>
        public struct Parameters
        {
            public double AmplitudeElectronsPerSecond;
            public double CharacteristicFluenceElectrons;
            public double FluenceWidthElectrons;
            public double Alpha;
            public double Gamma;
        }

        /// <summary>
        /// The Fermi parameters for a stimulus exposure of the given length, linearly interpolated
        /// on exposure time between the tabulated rows, as ISR 2015-15 prescribes.
        ///
        /// CLAMPED AT BOTH ENDS rather than extrapolated. The table spans 49 s to 1402 s; outside
        /// that the trends are known in direction but not in rate, and a linear extrapolation of
        /// gamma reaches zero (persistence that never decays) at a finite exposure time, which is
        /// not a physical prediction of anything. The endpoints are what the measurement supports.
        /// </summary>
        public static Parameters InterpolateParameters(double stimulusExposureSeconds)
        {
            int n = StimulusExposureSeconds.Length;

            if (!(stimulusExposureSeconds > StimulusExposureSeconds[0]))
                return Row(0);
            if (stimulusExposureSeconds >= StimulusExposureSeconds[n - 1])
                return Row(n - 1);

            int i = 0;
            while (i < n - 2 && stimulusExposureSeconds > StimulusExposureSeconds[i + 1]) i++;

            double t0 = StimulusExposureSeconds[i], t1 = StimulusExposureSeconds[i + 1];
            double f = (stimulusExposureSeconds - t0) / (t1 - t0);

            return new Parameters
            {
                AmplitudeElectronsPerSecond = Lerp(AmplitudeElectronsPerSecond, i, f),
                CharacteristicFluenceElectrons = Lerp(CharacteristicFluenceElectrons, i, f),
                FluenceWidthElectrons = Lerp(FluenceWidthElectrons, i, f),
                Alpha = Lerp(FluencePowerAlpha, i, f),
                Gamma = Lerp(DecayIndexGamma, i, f),
            };
        }

        private static Parameters Row(int i) => new Parameters
        {
            AmplitudeElectronsPerSecond = AmplitudeElectronsPerSecond[i],
            CharacteristicFluenceElectrons = CharacteristicFluenceElectrons[i],
            FluenceWidthElectrons = FluenceWidthElectrons[i],
            Alpha = FluencePowerAlpha[i],
            Gamma = DecayIndexGamma[i],
        };

        private static double Lerp(double[] v, int i, double f) => v[i] + f * (v[i + 1] - v[i]);

        /// <summary>
        /// The persistence rate in electrons per second, at a time <paramref name="elapsedSeconds"/>
        /// after the end of a stimulus exposure of length <paramref name="stimulusExposureSeconds"/>
        /// that left this pixel with a fluence of <paramref name="fluenceElectrons"/>.
        ///
        /// This is a RATE, which is what the published model returns and what makes it composable:
        /// the charge a following exposure collects from it is the rate integrated over that
        /// exposure, and Integrate below does the integral in closed form rather than by sampling.
        /// </summary>
        public static double RateElectronsPerSecond(
            double fluenceElectrons, double elapsedSeconds, double stimulusExposureSeconds)
        {
            if (!(fluenceElectrons > 0.0)) return 0.0;
            if (!(elapsedSeconds > 0.0)) return 0.0;

            Parameters p = InterpolateParameters(stimulusExposureSeconds);
            return RateElectronsPerSecond(fluenceElectrons, elapsedSeconds, p);
        }

        /// <summary>The same, with parameters already resolved, so a per-pixel loop resolves them once.</summary>
        public static double RateElectronsPerSecond(
            double fluenceElectrons, double elapsedSeconds, Parameters p)
        {
            if (!(fluenceElectrons > 0.0)) return 0.0;
            if (!(elapsedSeconds > 0.0)) return 0.0;
            if (!(p.CharacteristicFluenceElectrons > 0.0)) return 0.0;

            // The Fermi term. Written with the exponent negated as the paper writes it, and guarded
            // against overflow at large negative arguments: exp() of a few hundred is infinity in
            // double precision, and 1/(inf + 1) is zero, which is the right answer but arrives via
            // a NaN if the surrounding arithmetic is not careful.
            double z = -(fluenceElectrons - p.CharacteristicFluenceElectrons) / p.FluenceWidthElectrons;
            double fermi = z > 700.0 ? 0.0 : 1.0 / (Math.Exp(z) + 1.0);
            if (fermi <= 0.0) return 0.0;

            double fluenceTerm = Math.Pow(fluenceElectrons / p.CharacteristicFluenceElectrons, p.Alpha);
            double timeTerm = Math.Pow(elapsedSeconds / 1000.0, -p.Gamma);

            return p.AmplitudeElectronsPerSecond * fermi * fluenceTerm * timeTerm;
        }

        /// <summary>
        /// The charge, in electrons, that persistence deposits into an exposure running from
        /// <paramref name="fromSeconds"/> to <paramref name="toSeconds"/> after the end of the
        /// stimulus.
        ///
        /// IN CLOSED FORM, because only the time factor depends on t and it is a pure power law:
        /// the integral of (t/1000)^(-gamma) is 1000/(1-gamma) * (t/1000)^(1-gamma), with the
        /// logarithmic case at gamma exactly 1 handled separately. Sampling the rate at the middle
        /// of the exposure instead would be wrong by a percent or so on a long exposure taken
        /// shortly after the stimulus, which is exactly the case that matters.
        ///
        /// gamma sits near 1 across the whole table (0.921 to 1.269), so the near-singular branch is
        /// not a corner case here, it is the ordinary one; it is taken whenever |1-gamma| is small
        /// enough that the general form loses precision to cancellation.
        /// </summary>
        public static double IntegrateElectrons(
            double fluenceElectrons, double fromSeconds, double toSeconds, double stimulusExposureSeconds)
        {
            if (!(fluenceElectrons > 0.0)) return 0.0;
            if (!(toSeconds > fromSeconds)) return 0.0;
            if (!(fromSeconds > 0.0)) fromSeconds = 0.0;

            Parameters p = InterpolateParameters(stimulusExposureSeconds);

            double z = -(fluenceElectrons - p.CharacteristicFluenceElectrons) / p.FluenceWidthElectrons;
            double fermi = z > 700.0 ? 0.0 : 1.0 / (Math.Exp(z) + 1.0);
            if (fermi <= 0.0) return 0.0;

            double fluenceTerm = Math.Pow(fluenceElectrons / p.CharacteristicFluenceElectrons, p.Alpha);
            double scale = p.AmplitudeElectronsPerSecond * fermi * fluenceTerm;

            double a = fromSeconds / 1000.0, b = toSeconds / 1000.0;
            double oneMinusGamma = 1.0 - p.Gamma;

            double integralInKiloseconds;
            if (Math.Abs(oneMinusGamma) < 1e-6)
            {
                // gamma == 1 exactly: the integral of 1/t is a logarithm. A zero lower limit
                // diverges, which is real - the model is not valid at t = 0 - so the lower limit is
                // held at the first moment the model was fitted over rather than at zero.
                double lower = Math.Max(a, 1e-6);
                integralInKiloseconds = Math.Log(b / lower);
            }
            else
            {
                integralInKiloseconds =
                    (Math.Pow(b, oneMinusGamma) - Math.Pow(Math.Max(a, 0.0), oneMinusGamma)) / oneMinusGamma;
            }

            // The integral was taken in units of kiloseconds, so it is scaled back to seconds.
            return scale * integralInKiloseconds * 1000.0;
        }
    }
}
